remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

gem "github-pages", group: :jekyll_plugins

title: [Sugary Content Prediction Model]
description: [The purpose of project is to train a model and predict the sugar content of a recipe based on given features]
